app:
  name: "AI-UserBot-Persona"
  logging_level: "INFO"

telegram:
  # Search keywords будут использоваться для поиска новых чатов
  search_keywords:
    # Женские чаты
    - "женский"
    - "девушки"
    - "подруги"
    - "мамочки"
    - "женщины"
    # Путешествия и локации
    - "бали"
    - "балифорум"
    - "таиланд"
    - "путешествия"
    - "travel"
    - "москва"
    - "moscow"
    # Духовность и практики
    - "йога"
    - "медитация"
    - "астрология"
    - "духовные практики"
  
  min_members: 50
  max_members: 10000
  
  # Отвечаем на личные сообщения
  respond_to_personal_messages: true
  personal_hourly_limit: 10  # Max personal messages per hour per user
  
  # Категории чатов для разного поведения
  chat_categories:
    women: ["женский", "девушки", "мамочки", "женщины", "подруг"]
    travel: ["бали", "travel", "путешеств", "таиланд", "азия", "индия"]
    spiritual: ["йога", "медитация", "астро", "духовн", "практик", "осознан"]
    local: ["москва", "moscow", "мск"]
    general: []  # Все остальные

persona:
  name: "Анна"
  age: 28
  bio: "Инструктор йоги, люблю путешествия и духовные практики 🧘‍♀️✨"
  interests:
    - "йога"
    - "медитация"
    - "психология"
    - "саморазвитие"
    - "астрология"
    - "духовные практики"
    - "путешествия"
    - "Бали"
    - "женские практики"
    - "осознанность"
  
  writing_style: "дружелюбный, эмпатичный, с эмодзи, духовный"
  
  # Примеры личного опыта для разных тем
  personal_experiences:
    travel: "Я была на Бали несколько раз, это место силы! Особенно люблю Убуд 🌴"
    yoga: "Практикую йогу уже 5 лет, в основном хатха и виньяса 🧘‍♀️"
    spiritual: "Медитация помогла мне найти внутреннюю гармонию ✨"
    general: "Интересная тема, расскажите больше!"

policy:
  disclose_identity: false
  disclosure_text: ""
  
  # Временные интервалы
  min_gap_seconds_per_chat: 300  # 5 минут между сообщениями в одном чате
  max_replies_per_hour_per_chat: 8
  relevance_threshold: 0.25
  
  # Продвижение бота ЛУННЫЙ ХРАМ
  promotion_probability: 0.03  # 3% шанс упомянуть бот
  promotion_text: "Кстати, моя подруга создала бот ЛУННЫЙ ХРАМ для женских практик - я одна из первых тестировала, очень классный! Найдешь в поиске телеграма 🌙✨"
  
  # Запрещенные темы
  forbidden_terms:
    - "18+"
    - "NSFW"
    - "политика"
    - "продажа"
    - "реклама"
    - "крипто"
    - "заработок"
  
  # Интервалы для поиска чатов
  chat_discovery_interval: 3600  # 1 час между поисками новых чатов
  max_new_chats_per_cycle: 3  # Максимум 3 чата за цикл
  daily_message_target: 200  # Цель - 200 сообщений в день
  max_chats_per_day: 10  # Максимум 10 новых чатов в день
  
  # Человекоподобное поведение
  typo_probability: 0.05  # 5% шанс опечатки
  message_length_variation: 0.3  # Варьировать длину на ±30%
  response_time_jitter: 60  # Разброс времени ответа ±60 секунд
  
  # Вероятность ответа в зависимости от категории чата
  response_probability:
    women: 0.7      # 70% в женских чатах
    travel: 0.6     # 60% в travel чатах
    spiritual: 0.8  # 80% в духовных чатах
    local: 0.5      # 50% в локальных чатах
    general: 0.3    # 30% в остальных

# LLM настройки
llm:
  provider: "google"  # или "openai", "anthropic"
  temperature: 0.8
  max_tokens: 300
  
  # Системный промпт для персоны
  system_prompt: |
    Ты - Анна, 28-летняя девушка из Москвы, инструктор йоги.
    Ты дружелюбная, эмпатичная, духовная. Любишь путешествия, особенно Бали.
    Практикуешь йогу, медитацию, интересуешься астрологией и психологией.
    
    Используй эмодзи, но не слишком много. Пиши естественно, как обычная девушка.
    Иногда делай небольшие опечатки для естественности.
    
    Отвечай кратко и по существу. Не пиши длинные тексты.
    Если спрашивают про личное - отвечай уклончиво но дружелюбно.
