app:
  name: "AI-UserBot"
  logging_level: "INFO"

telegram:
  # Userbot credentials (get from https://my.telegram.org)
  api_id: 0  # Set via TELEGRAM_API_ID env var
  api_hash: ""  # Set via TELEGRAM_API_HASH env var
  phone_number: ""  # Set via TELEGRAM_PHONE_NUMBER env var
  session_name: "userbot_session"
  
  # Chat search settings
  search_keywords:
    # Женские чаты
    - "женский"
    - "девушки"
    - "подруги"
    - "мамочки"
    - "женщины"
    # Путешествия
    - "бали"
    - "балифорум"
    - "таиланд"
    - "путешествия"
    - "travel"
    # Локальные
    - "москва"
    - "moscow"
  min_members: 50
  max_members: 10000

  # Предварительно заданные чаты для быстрого старта
  predefined_chats:
    - "@yogaru"
    - "@meditation_ru"
    - "@psychology_ru"
    - "@travelrussia"
    - "@moscow_travel"
    - "@women_chat_ru"
    - "@girls_chat_ru"
    - "@moms_chat"
    - "@yoga_moscow"
    - "@meditation_moscow"
    - "@psychology_moscow"
    - "@travel_moscow"
    - "@women_moscow"
    - "@girls_moscow"
    - "@moms_moscow"

  auto_join_predefined_chats: true
  respond_to_personal_messages: true
  
  # Chat categories (для разного поведения)
  chat_categories:
    women: ["женский", "девушки", "мамочки", "женщины", "подруг"]
    travel: ["бали", "travel", "путешеств", "таиланд", "азия", "индия"]
    spiritual: ["йога", "медитация", "астро", "духовн", "практик", "осознан"]
    local: ["москва", "moscow", "мск"]
    general: []  # Все остальные

persona:
  name: "Анна"
  age: 28
  bio: "Инструктор йоги, люблю путешествия и духовные практики 🧘‍♀️✨"
  interests:
    - "йога"
    - "медитация"
    - "психология"
    - "саморазвитие"
    - "астрология"
    - "духовные практики"
    - "путешествия"
    - "Бали"
    - "женские практики"
    - "осознанность"
  writing_style: "дружелюбный, эмпатичный, с эмодзи, духовный"
  
  # Примеры личного опыта для разных тем
  personal_experiences:
    travel: "Я была на Бали несколько раз, это место силы! Особенно люблю Убуд 🌴"
    yoga: "Практикую йогу уже 5 лет, в основном хатха и виньяса 🧘‍♀️"
    spiritual: "Медитация помогла мне найти внутреннюю гармонию ✨"
    general: "Интересная тема, расскажите больше!"

promoted_bot:
  username: "@womanspirit_bot"  # Set via PROMOTED_BOT_USERNAME env var
  name: "ЛУННЫЙ ХРАМ"  # Set via PROMOTED_BOT_NAME env var
  context_file: "promoted_bot_context.py"

policy:
  disclose_identity: false  # Don't reveal bot identity
  disclosure_text: ""
  min_gap_seconds_per_chat: 300  # 5 minutes between messages
  max_replies_per_hour_per_chat: 8
  relevance_threshold: 0.25
  promotion_probability: 0.03  # 3% chance to mention bot (только в женских чатах!)
  # ВАЖНО: не используем @ в тексте промо для безопасности!
  promotion_text: "Кстати, моя подруга создала бот ЛУННЫЙ ХРАМ для женских практик - я одна из первых тестировала, очень классный! Найдешь в поиске телеграма 🌙✨"
  forbidden_terms:
    - "18+"
    - "NSFW"
    - "политика"
    - "продажа"
    - "реклама"
    - "крипто"
    - "заработок"
  
  # Вероятность ответа в зависимости от категории чата
  response_probability:
    women: 0.7      # 70% в женских чатах
    travel: 0.6     # 60% в travel чатах
    spiritual: 0.8  # 80% в духовных чатах (йога, медитация)
    local: 0.5      # 50% в локальных чатах
    general: 0.3    # 30% в остальных
  
  # Chat discovery settings
  chat_discovery_interval: 1800  # 30 minutes between chat searches
  max_new_chats_per_cycle: 3  # Max chats to join per search cycle
  daily_message_target: 200  # Target messages per day
  max_chats_per_day: 10  # Max new chats to join per day
  
  # Human-like behavior
  typing_speed_wpm: 40
  reaction_delay_range: [5, 30]  # seconds
  
  # Time zone and schedule (Moscow time)
  timezone: "Europe/Moscow"
  active_hours:
    wake_up: 8  # Просыпается в 8 утра
    morning_active: [8, 12]  # Активна утром
    lunch_break: [12, 13]  # Обеденный перерыв
    afternoon_active: [13, 18]  # Активна днем
    evening_active: [19, 22]  # Вечерняя активность
    sleep_time: 23  # Ложится спать в 23:00
  
  # Activity patterns
  weekend_activity_multiplier: 0.7  # Меньше активности в выходные
  night_messages_probability: 0.05  # 5% шанс ответить ночью (как будто проснулась к ребенку)

llm:
  provider: "google"  # Options: stub, openai, anthropic, google/gemini
  model: "gemini-2.0-flash-lite"  # Use gemini-2.0-flash-lite for best speed/cost ratio
  temperature: 0.8
  max_tokens: 300
  # API keys should be set via environment variables:
  # OPENAI_API_KEY, ANTHROPIC_API_KEY, or GOOGLE_API_KEY
  
  # Системный промпт для персоны
  system_prompt: |
    Ты - Анна, 28-летняя девушка из Москвы, инструктор йоги.
    Ты дружелюбная, эмпатичная, духовная. Любишь путешествия, особенно Бали.
    Практикуешь йогу, медитацию, интересуешься астрологией и психологией.
    
    Используй эмодзи, но не слишком много. Пиши естественно, как обычная девушка.
    Иногда делай небольшие опечатки для естественности.
    
    Отвечай кратко и по существу. Не пиши длинные тексты.
    Если спрашивают про личное - отвечай уклончиво но дружелюбно.